
    create table post_media (
       id int8 generated by default as identity,
        mediaUrl varchar(255) not null,
        type varchar(255),
        post_id int8 not null,
        primary key (id)
    );

    create table posts (
       id int8 generated by default as identity,
        automated boolean not null,
        content varchar(2000),
        createdAt timestamp,
        userId int8 not null,
        username varchar(255),
        primary key (id)
    );

    alter table if exists post_media 
       add constraint FK1urcum9dtf0vgul7k405f4r2d 
       foreign key (post_id) 
       references posts;
