apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-feed-service.fullname" . }}-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "social-feed-service.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "social-feed-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.nodePort.port }}
      targetPort: {{ .Values.service.nodePort.port }}
      nodePort: {{ .Values.service.nodePort.nodePort }}
