CREATE SCHEMA IF NOT EXISTS social_feed_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA social_feed_service GRANT ALL PRIVILEGES ON TABLES TO hikuuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA social_feed_service GRANT ALL PRIVILEGES ON SEQUENCES TO hikuuser;