
    create table social_feed_service.follows (
       id int8 generated by default as identity,
        createdAt timestamp not null,
        follower_id int8 not null,
        following_id int8 not null,
        primary key (id)
    );

    create table social_feed_service.post_media (
       id int8 generated by default as identity,
        mediaUrl varchar(255) not null,
        type varchar(255),
        post_id int8 not null,
        primary key (id)
    );

    create table social_feed_service.posts (
       id int8 generated by default as identity,
        automated boolean not null,
        content varchar(2000),
        createdAt timestamp,
        title varchar(255),
        userId int8 not null,
        username varchar(255),
        primary key (id)
    );

    alter table if exists social_feed_service.follows 
       add constraint UK4faelgsm2rxl2jf3iyjy981ro unique (follower_id, following_id);

    alter table if exists social_feed_service.post_media 
       add constraint FK1urcum9dtf0vgul7k405f4r2d 
       foreign key (post_id) 
       references social_feed_service.posts;
