replicaCount: 1

image:
  repository: social-feed-service
  tag: dev-latest
  pullPolicy: Never

service:
  clusterIP:
    port: 8091

  nodePort:
    port: 8091
    nodePort: 30091

flyway:
  image:
    repository: social-feed-service-migrator
    tag: "dev"
  url: jdbc:postgresql://postgres.database.svc.cluster.local:5432/hikudb
  user: hikuuser
  password: hikupassword
  baselineOnMigrate: true
  baselineVersion: 1

rabbitmq:
  host: rabbitmq.platform.svc.cluster.local
  port: 5672
  user: hikuuser
  password: hikupassword