replicaCount: 1

image:
  repository: social-feed-service
  tag: dev-latest
  pullPolicy: Never

database:
  enabled: true
  host: postgres.database.svc.cluster.local
  port: "5432"
  name: hikudb
  schema: social_feed_service

azure:
  enabled: false

service:
  clusterIP:
    port: 8091

  nodePort:
    enabled: true
    port: 8091
    nodePort: 30091

flyway:
  image:
    repository: social-feed-service-migrator
    tag: "dev"
  url: jdbc:postgresql://postgres.database.svc.cluster.local:5432/hikudb
  user: hikuuser
  password: hikupassword
  baselineOnMigrate: true
  baselineVersion: 1

rabbitmq:
  host: rabbitmq.platform.svc.cluster.local
  port: 5672
  user: hikuuser
  password: hikupassword

jwtAuth:
  issuer: "http://localhost:8080/auth/realms/hiku-dev"
  jwksUri: "http://keycloak.keycloak.svc.cluster.local:8080/auth/realms/hiku-dev/protocol/openid-connect/certs"